### ISSUE TITLE
If set vertical left, panel no longer shows « underlining » for running app’s?

### ISSUE THREAD

**Issue by Coeur-Noir** [UbuntuBudgie/pocillo-gtk-theme#4] opened 2018-06-11 09:26 UTC
Hi,

Ubuntu-Budgie 18.04 here.

when at horizontal bottom screen, icon task list in a pocillo themed panel shows underlining for running app’s, in minimized windows.
( if size of panel is big enough, though ).

If set to vertical left side of screen, there is no way to see those underlining, whatever size of panel.
![pocillo_panel_underlining](https://user-images.githubusercontent.com/1895947/41223355-d61b4b8e-6d69-11e8-8013-84fb1911b04a.png)
I'd expect some underlining at the left of icon for running app's.

**Comment by fossfreedom** [comment] 2018-07-11 13:31
odd - I cannot reproduce this

![dots](https://user-images.githubusercontent.com/996240/42574729-089caf20-8517-11e8-86bb-5ac10fc3b994.png)

so dots for minimised and line for visible apps.

**Comment by fossfreedom** [comment] 2018-07-11 13:43
ah - ignore that. Can now reproduce.

**Comment by fossfreedom** [comment] 2018-07-11 14:30
fixed in git ^^^

**Closed by fossfreedom** 2018-07-11 14:30 UTC
Labels: good first issue, help wanted

**Comment by Coeur-Noir** [comment] 2018-07-21 01:13
Sorry to come back here :-/ but when trying to install from git…
```
coeur-noir@asgard:~/pocillo-gtk-theme$ make
** Matching Colors
cd ./src/gtk-3.0/gtk-common/ && ./recolor-assets.sh > /dev/null
** Generating GTK2...
#cd ./src/gtk-2.0 && ./recolor-assets.sh
** Generating GTK3...
for color in '' '-dark' '-light'; do \
  for size in '' '-slim'; do \
    for version in '3.22'; do \
      sassc -M -t expanded src/gtk-3.0/$version/gtk$color$size.{scss,css}; \
    done; \
  done; \
done
** Generating GNOME Shell...
for color in '' '-dark' '-light'; do \
  for size in '' '-slim'; do \
    # Skip gnome-shell 3.20 and 3.22 \
    for version in '3.24' '3.26'; do \
      sassc -M -t expanded src/gnome-shell/$version/gnome-shell$color$size.{scss,css}; \
      sassc -M -t expanded src/gnome-shell/$version/extensions/workspaces-to-dock/workspaces-to-dock.{scss,css}; \
      sassc -M -t expanded src/gnome-shell/$version/pad-osd.{scss,css}; \
    done; \
  done; \
done
** Generating the CSS...
** Generating the Assets...
cd ./src/gtk-3.0/gtk-common/ && find . -type f -name *.png -exec rm -v '{}' + > /dev/null
cd ./src/gtk-2.0/ && find . -type f -name *.png -exec rm -v '{}' + > /dev/null
cd ./src/gtk-3.0/gtk-common/ && ./render-assets.sh > /dev/null
Gtk-Message: 03:07:59.728: Failed to load module "canberra-gtk-module"

(inkscape:8436): dbind-WARNING **: 03:07:59.731: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Gtk-Message: 03:08:00.058: Failed to load module "canberra-gtk-module"

and repeating repeating repeating…
```
My mistake ?

**Comment by fossfreedom** [comment] 2018-07-21 04:40
No. And no need to worry. Can be safely ignored

On Sat, 21 Jul 2018, 02:13 Cœur Noir, <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry to come back here :-/ but when trying to install from git…

coeur-noir@asgard:~/pocillo-gtk-theme$ make
** Matching Colors
cd ./src/gtk-3.0/gtk-common/ && ./recolor-assets.sh > /dev/null
** Generating GTK2...
#cd ./src/gtk-2.0 && ./recolor-assets.sh
** Generating GTK3...
for color in '' '-dark' '-light'; do \
  for size in '' '-slim'; do \
    for version in '3.22'; do \
      sassc -M -t expanded src/gtk-3.0/$version/gtk$color$size.{scss,css}; \
    done; \
  done; \
done
** Generating GNOME Shell...
for color in '' '-dark' '-light'; do \
  for size in '' '-slim'; do \
    # Skip gnome-shell 3.20 and 3.22 \
    for version in '3.24' '3.26'; do \
      sassc -M -t expanded src/gnome-shell/$version/gnome-shell$color$size.{scss,css}; \
      sassc -M -t expanded src/gnome-shell/$version/extensions/workspaces-to-dock/workspaces-to-dock.{scss,css}; \
      sassc -M -t expanded src/gnome-shell/$version/pad-osd.{scss,css}; \
    done; \
  done; \
done
** Generating the CSS...
** Generating the Assets...
cd ./src/gtk-3.0/gtk-common/ && find . -type f -name *.png -exec rm -v '{}' + > /dev/null
cd ./src/gtk-2.0/ && find . -type f -name *.png -exec rm -v '{}' + > /dev/null
cd ./src/gtk-3.0/gtk-common/ && ./render-assets.sh > /dev/null
Gtk-Message: 03:07:59.728: Failed to load module "canberra-gtk-module"

(inkscape:8436): dbind-WARNING **: 03:07:59.731: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Gtk-Message: 03:08:00.058: Failed to load module "canberra-gtk-module"

and repeating repeating repeating…


My mistake ?

**Comment by Coeur-Noir** [comment] 2018-07-21 10:46
O you mean it will stop repeating ? I may have not waited long enough, it looked that it would never stop to me… I will retry.

**Comment by fossfreedom** [comment] 2018-07-21 11:04
It is creating the assets. Depending upon the speed of your computer it will take a few minutes to complete
